apiVersion: apps/v1
kind: Deployment
metadata:
  name: mymvapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mymvapp
  template:
    metadata:
      labels:
        app: mymvapp
    spec:
      containers:
        - name: mymvapp
          image: nikshay7891/mymvcapp:latest
          ports:
            - containerPort: 8081  # Change to 8081
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
