apiVersion: v1
kind: Service
metadata:
  name: mymvapp-service
spec:
  type: LoadBalancer
  selector:
    app: mymvapp
  ports:
    - protocol: TCP
      port: 80  # External access port
      targetPort: 8081  # Change to 8081
